# Generated by Django 4.2 on 2024-10-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
            ],
            options={"db_table": "category",},
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="goods_images"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("discount", models.IntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("brand", models.CharField(max_length=200)),
                (
                    "release_form",
                    models.CharField(
                        choices=[
                            ("tabs", "Tablets"),
                            ("caps", "Capsules"),
                            ("pow", "Powder"),
                            ("tof", "Toffees"),
                            ("tc", "Tablets and Capsules"),
                            ("tcp", "Tablets, capsules and powder"),
                            ("ot", "Other"),
                        ],
                        default="Capsules",
                        max_length=120,
                    ),
                ),
                (
                    "course_duration",
                    models.IntegerField(blank=True, default="30", max_length=120),
                ),
                ("expiration_date", models.DateTimeField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categories",
                    ),
                ),
            ],
            options={"db_table": "product",},
        ),
    ]
