# Generated by Django 4.2 on 2024-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_products_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="course_duration",
            field=models.IntegerField(blank=True, default="30"),
        ),
    ]
